# Generated by Django 3.2.6 on 2021-08-26 07:26

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=32, verbose_name='签名')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('create_time', models.IntegerField(blank=True, default=time.time, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.TextField(default='匿名', max_length=32, verbose_name='作者')),
                ('title', models.TextField(verbose_name='标题')),
                ('desc', models.TextField(verbose_name='描述')),
                ('config', models.TextField(default='{}', verbose_name='配置文件')),
                ('create_time', models.IntegerField(blank=True, default=time.time, verbose_name='创建时间')),
                ('last_download', models.IntegerField(blank=True, default=time.time, verbose_name='最后下载时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configs.user')),
                ('user_like', models.ManyToManyField(blank=True, related_name='user_like', to='configs.User', verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
            },
        ),
    ]
